function [ score ] = test( X_test, Y_test, W1, W2 )
%TEST test the model generated by the MLP network in the training section
%   Testing each sample from the test data in order to see if the model
%   classifies the data correctly.

    bias  = 1;
    score = 0;
    Y_out = ones(size(Y_test));

    for i = 1 : length(X_test)
        % Computing the output from the hidden layer.
        hiddenlayerInput = W1 * X_test(i,:)';
        Y = [bias; logsig(hiddenlayerInput)];

        % Computing the output from the output layer.
        outputlayerInput = W2 * Y;
        Y_out(i,:) = logsig(outputlayerInput)';

        % Binarizing each activation from the output 'Y_out'.
        Y_out(i,:) = evaluate(Y_out(i,:)');

        % Increments the score if the classification is correct.
        score = score + isequal(Y_out(i,:), Y_test(i,:));
    end

end
